name: E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install global CLI tools
        run: npm install -g wait-on

      - name: Build frontend with test variables
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_TESTING_VARIABLES: true
        run: bun run build

      - name: Install Playwright
        run: |
          bun add -D @playwright/test
          npx playwright install --with-deps

      - name: Serve frontend locally
        run: |
          bun add -D serve
          npx serve -s dist -l 3000 &

      - name: Wait for frontend
        run: wait-on http://localhost:3000

   

      - name: Run Playwright tests
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_TESTING_VARIABLES: true
        run: bun run e2e:ci



      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report
